### ISSUE TITLE
wax安卓端 图片下载地址是在哪里？

### ISSUE THREAD

**Issue by lovewanjiayun** [niuhuan/wax#18]
。。。。。

**Comment by niuhuan** [comment]
`///file://data/data/opensource.wax/downloads`

**Comment by lovewanjiayun** [comment]
> `///file://data/data/opensource.wax/downloads`

找不到，我有两台手机，试过了深度检索找不到任何文件夹名称含有wax或者opensource

**Comment by lovewanjiayun** [comment]
。。。

**Comment by niuhuan** [comment]
需要取得root权限，是文件系统而不是SD卡根目录。详细信息需要参照安卓开发者官网。

**Comment by lovewanjiayun** [comment]
我的手机比较特殊无法root，还有别的解决方法么

**Comment by niuhuan** [comment]
- 可以查询谷歌的文档或者咨询一下手机生产厂家。
- 或者使用其他设备或应用程序。本软件的下载只是缓存漫画的功能。
- 对Root功能没有所了解修改程序资料可能会造成应用程序无法运行
