### ISSUE TITLE
win版无法使用

### ISSUE THREAD

**Issue by cloudcat214** [niuhuan/wax#2]
![image](https://user-images.githubusercontent.com/99686044/174358178-3914e0e6-2bfa-4dec-b285-012d97872ed6.png)
打开后就一直是这样，我的防火墙会监控联网请求的，但是软件就是没有任何联网请求，安卓版一安装完毕就能正常使用。

换了0.0.2版也是一样。这是我反馈的版本
![image](https://user-images.githubusercontent.com/99686044/174358876-201a9fd7-b376-44ff-b7f5-6563c7e264b6.png)

麻烦大佬修复，感谢大佬！

**Comment by cloudcat214** [comment]
感谢大佬修复了联网问题，不过，还是看不了呢。
![image](https://user-images.githubusercontent.com/99686044/174443239-5b4ce266-6c43-454f-9655-fe18a18367a4.png)
打开所有的内容，都是这样的画面。

**Comment by niuhuan** [comment]
已修复
