### ISSUE TITLE
搜寻出现错误

### ISSUE THREAD

**Issue by playtravian** [niuhuan/wax#21]
大佬先谢谢你的专案，很好的使用者介面以及体验。

最近在搜寻的时候有时候会出现错误，如下图，希望能解决一下，谢谢。
![image](https://github.com/niuhuan/wax/assets/135101363/9a8a6ce0-a91b-473f-bf96-2cb0d5d259ee)
搜寻词在此: ゆいちゃんねる

另外还想许几个愿望:
1. 希望能在预览/或是点入漫画的时候能看到漫画的页数，跟网页一样。
2. 还希望可以选取漫画的名字(方便复制)
3. 支援删除收藏漫画的功能

先谢谢大佬了。

**Comment by niuhuan** [comment]
已经找到搜索错误的原因, 近期会修复一下。
其他的问题视难易程度决定是否修改。
长按可以删除收藏的漫画或者复制名字?

**Comment by playtravian** [comment]
谢谢大佬，这修复跟完成愿望的速度好牛阿。

另外一点小建议，我想关于复制的部分可以不用确认，长案直接复制就可以了。

再次谢谢大佬🙏
