### ISSUE TITLE
漫画下载及显示问题

### ISSUE THREAD

**Issue by Frainstak** [niuhuan/wax#27]
大部分漫画下载及查看功能完好，但是部分漫画下载时下载到中间失败，无法下载的页显示为红色大叉，重新开始下载亦无效，卸载重装，清除缓存/数据，更换分流，开关梯子等均无法解决，如
[クレージュアクセル] 殲光のイクス-Disorder Eclipse- [村长和热心村民联合汉化]
这本本子，大量页面为红色大叉，附图，A14系统，同时在wnacg上这本本子可以完整显示
![微信图片_20240316200928](https://github.com/niuhuan/wax/assets/163650712/f0b78a7d-bb57-44be-a390-060fa6ce1534)

**Comment by niuhuan** [comment]
感谢您的反馈，猜测是图片格式不标准，客户端无法解析，修复比较困难，短期内无法解决。
