### ISSUE TITLE
大佬请问能在自动清理中加入永不选项吗

### ISSUE THREAD

**Issue by YouGuess11111111** [niuhuan/wax#4]
版本安卓，请问能在大佬所有的漫画软件中都在自动清理中加入永不选项吗，非常感谢

**Comment by niuhuan** [comment]
这个需求是不是用 “离线模式” 称呼更恰当?

**Comment by YouGuess11111111** [comment]
那是我理解错了，我以为会把历史记录也自动清理，因为我会把历史记录当成二级收藏夹来用

如果只是图片之类浏览产生的缓存倒是无所谓，毕竟已经有了下载功能

**Comment by niuhuan** [comment]
有下载嘛？软件太多我已经记不清了

**Comment by YouGuess11111111** [comment]
别的下载都挺完善的，wax作品页有下载选项但找不到下载列表

不过自动清理没啥问题了我就close了，谢谢大佬
