### ISSUE TITLE
下载漫画的位置

### ISSUE THREAD

**Issue by myNameJavaLover** [niuhuan/wax#6]
您好开发者，我是m系列芯片macOS的使用者，我想知道通过wax软件下载后的漫画在电脑中保存的位置方便管理。或者可否在下次更新中在客户端的下载漫画界面中添加删除已下载漫画的本子

**Comment by niuhuan** [comment]
暂时没有办法导出. 以后更新会考虑导出功能.

**Comment by niuhuan** [comment]
如果长按不能删除, 就是还不能删除, 开发过什么功能, 我有时候也记不清楚, 项目太多啦

**Comment by myNameJavaLover** [comment]
目前长按是无法删除的，十分感谢您的回复。

**Comment by niuhuan** [comment]
删除已经加好了, 导入导出, 需要等, 具体时间不详.

**Comment by myNameJavaLover** [comment]
好的，感谢大佬
